name: Daily Italian Learning Agent

on:
  schedule:
    - cron: "0 6 * * *"  # 7h du matin à Paris (UTC+1) — décalé d'1h par rapport au grec
  workflow_dispatch:  # Pour déclencher manuellement si besoin

jobs:
  run-agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      
      # Installation de ffmpeg et des dépendances système pour WeasyPrint
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg libpango-1.0-0 libpangoft2-1.0-0 libharfbuzz0b libfontconfig1
      
      # Installation des dépendances Python
      - name: Install dependencies
        run: pip install mistralai python-dotenv edge-tts pydub weasyprint
      
      # Exécution du script
      - name: Run agent
        env:
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        run: python IA_agent/italienAgent/main.py
